---
conditions: v1
dist: xenial

git:
  depth: 200

cache:
  bundler: true
  pip: true
  directories:
    - $HOME/.cache/pre-commit
    - $HOME/.pre-commit
    - $HOME/.rvm
    - $HOME/Library/Caches/Homebrew

services:
  - docker

language: python

.mixtures:  # is not used by Travis CI, but helps avoid duplication
  - &if-cron-or-manual-run-or-tagged
    if: type IN (cron, api) OR tag IS present
  - &py-36
    python: "3.6"
  - &py-37
    python: "3.7"
  - &py-38
    python: "3.8"
  - &reset-prerequisites
    addons: {}
    before_install:
      - pip install tox-venv tox-tags
    before_script: []
    services: []
  - &lint
    <<: *py-38
    <<: *reset-prerequisites

jobs:
  fast_finish: true

  include:
    - <<: *lint
      name: linting the code
      env:
        - TOXENV=lint

    - <<: *py-38
      env:
        - TOXENV=devel

    - <<: *py-37
      <<: *if-cron-or-manual-run-or-tagged
      env:
        - TOXENV=devel

    - <<: *py-36
      <<: *if-cron-or-manual-run-or-tagged
      env:
        - TOXENV=devel


    - &deploy-job
      <<: *py-38
      <<: *reset-prerequisites
      stage: Deploy
      name: Publishing current Git tagged version of dist to PyPI
      if: repo == "pycontribs/molecule-inspec" AND tag IS present
      env:
        - TOXENV=build-dists
      before_deploy:
        - echo > setup.py
      deploy: &deploy-step
        provider: pypi
        user: ansible-molecule
        password:
          secure: >
            HPBkDwncLYLEzxirPfNB88GYFWZ/wA1jMgCd4wT7SgKQlIyRSCT6KXMfoOUVMH/uwaLggoURaGtmD/qnrfXj+bG15nBCCOaIZdXzODln/PwDFAYT8ZspzRPzQOfncdk4WTsVbwpiGgpdm+TxGGBz8yedvVXiTwmwLCGC0FsAE8Wp8krNH1Kwqp3OaZeePakIbEj0UXgCTnAol3ZgVWWy+6bfDBb/aLiGXjsAIb7sY6HzwvQUr43xFO7tReaGO23mGwgIy/tNstXarwxezlw6FlGe5KJGvE/a4yAPuWg9kuJt5MqwbCJzhP38SeH4Gc6x0o6jPT/+NbvLV1ck1Qbz5gCYmXlOzucDP+P5t8E3g+zJbNbCR00k1BpG3MIEzrHeyp/hCdDYnGB3TVnlj+L4Y/yoUdCq9FJI8xHLbj/fMe5vxBMMsvDbt2JJReavi3WB2pv2nHtivkKj/Kow4FRm+Kp3WH4x5NlZDjV5gsUbwPcN1kIpb09sPZE2wYugvCTOiExt7mdd0JMMcgxuR1jGgGxqRARQeqjz14VVNsrVIIrMh8JX8u7Rl9sqmU4UuLGTxnq2cwyBmYzJ0gmDgN3TvQ96n9D2sP0YQj35v7RY5vsdYsfLucLdTfTajP9OL4Bw+ogXMJrArIq+j+7uJyTFqNdAN+Y6nX7WV0W6rp8aA1I=
        distributions: dists
        skip-cleanup: true
        "on":
          all_branches: true

addons:
  apt:
    packages:
      - lxc
      - lxc-dev
      - lxd
      - lxd-client
before_install:
  - pip install tox-tags
before_script:
  - gem install inspec -v '~> 3'
  - gem install rubocop -v '~> 0.69.0'
script:
  - tox
